### ISSUE TITLE
Coordinator error handling

### ISSUE THREAD

**Issue by vimwitch** [zkopru-network/zkopru#364] opened 2022-01-17 21:39 UTC
```
[1642397256587] ERROR (1 on 1ebae18a880e): Uncaught error in task
[1642397256587] ERROR (1 on 1ebae18a880e): Invalid value.  does not start with 0x
    Error: Invalid value.  does not start with 0x
        at Bytes32.HexString [as constructor] (/src/node_modules/soltypes/build/index.js:4059:19)
        at new Bytes32 (/src/node_modules/soltypes/build/index.js:4680:28)
        at Function.Bytes32.from (/src/node_modules/soltypes/build/index.js:4686:16)
        at Object.mergeDeposits (/src/packages/utils/dist/index.js:205:36)
        at L2Chain.<anonymous> (/src/packages/core/dist/context/layer2.js:240:49)
        at Generator.next (<anonymous>)
        at fulfilled (/src/packages/core/dist/context/layer2.js:5:58)
```

This error is occurring on the coordinator for the testnet.

**Comment by sifnoc** [comment] 2022-01-19 16:40
I re-produced this issue by dropping the deposit on purpose. 

A very possible scenario is that the coordinator cannot find deposits by the `queueAt` [here](https://github.com/zkopru-network/zkopru/blob/57ceb6a8f1b0f4d75feb451cc7fe935a76e14b5c/packages/core/src/context/layer2.ts#L295-L297), on the `Deposit` table when generating block due to the synchronizer could not finish  [`handleDepositEvents`](https://github.com/zkopru-network/zkopru/blob/57ceb6a8f1b0f4d75feb451cc7fe935a76e14b5c/packages/core/src/node/synchronizer.ts#L469-L495) for updating deposits on the `Deposit` table yet.

**Comment by JChanceHud** [comment] 2022-01-19 17:11
This problem continues to happen after the node is done synchronizing. I was looking at this again and I think it will happen if you call [mergeDeposits](https://github.com/zkopru-network/zkopru/blob/b07eb0305a43084d9492c896cecf4a08ff1ce72d/packages/utils/src/index.ts#L211) with an empty array. This should be happening [here](https://github.com/zkopru-network/zkopru/blob/main/packages/core/src/context/layer2.ts#L298).

**Comment by JChanceHud** [comment] 2022-01-19 17:13
Also, [this is the commit](https://github.com/zkopru-network/zkopru/blob/b07eb0305a43084d9492c896cecf4a08ff1ce72d/packages/core/src/context/layer2.ts#L285) that the testnet Zkopru node is running.

**Comment by sifnoc** [comment] 2022-01-19 17:21
> This problem continues to happen after the node is done synchronizing

Could you give me more details about this for reproducing this issue on my side?

> I was looking at this again and I think it will happen if you call mergeDeposits with an empty array. This should be happening here.

Yes, exactly, It happen when run `mergeDeposits([])`

**Comment by JChanceHud** [comment] 2022-01-19 17:32
I'm not sure about reproducing from scratch, but you can grab the database file from the testnet coordinator and use it locally. The database file is available on the Zkopru server at `/home/chance/database21.sqlite`

**Closed** 2022-02-16 14:18 UTC
